### ISSUE TITLE
Single quotation marks are escaped incorrectly in JSON mode

### ISSUE THREAD

**Issue by mumez** [GsDevKit/ston#18]
In JSON mode, single quotation marks are escaped incorrectly. 

`STON toJsonString: 'steve''s job'.` 

![2023-06-26 13_55_44-localhost_3390 - リモート デスクトップ接続](https://github.com/GsDevKit/ston/assets/705350/11622a74-cfb4-4c5c-ac31-204057a5523f)

$\ is not needed in this case. It should be `"steve's job"`

Please update STONWriter>>encodeCharacter: char as in Pharo.

In Pharo 11, 

![2023-06-26 14_00_56-C__Users_ume_Documents_Pharo_images_Pharo 11 0 - Meilisearch st_Pharo 11 0 - Mei](https://github.com/GsDevKit/ston/assets/705350/50fa9de5-b4f4-487e-a034-288e62a7a98f)

**Comment by dalehenrich** [comment]
Thanks for the report @mumez ! I'm busy at the moment, but will get to this when things settle down a bit ... if it is critical, could you submit a pull request?

**Comment by mumez** [comment]
I happened to find the issue while writing a test for Meilisearch.st.
https://github.com/mumez/Meilisearch.st
Since I've changed my test fixture already, it is not critical.  
I can submit a quick fix, but Pharo's STON seems to have other improvements. So I think it's better to update the whole thing.

**Comment by dalehenrich** [comment]
I have to be careful about changing STON ... the Pharo folks have a habit of making API breaking changes and There's an expectation by a number of tools that interact with multiple versions of GemStone that the API is relatively stable ...

With that said ... outright bugs should be fixed :smiley:

**Comment by mumez** [comment]
OK I sent the PR: https://github.com/GsDevKit/ston/pull/19
Please check it. 
It is based on the current Pharo version, but with minimal changes.

**Comment by dalehenrich** [comment]
tests are now passing
